# Package

In [1]:
import smdir

smdir.load_table(smdir.tables.tsetmc.price)

,priceChange,priceMin,priceMax,priceYesterday,priceFirst,last,id,insCode,dEven,hEven,pClosing,iClose,yClose,pDrCotVal,zTotTran,qTotTran5J,qTotCap,received_time
0,0.0,0.0,0.0,713000.0,0.0,False,0,3955137492069792,20231220,61155,713000.0,False,True,713000.0,0.0,0.0,0.0,2023-12-21 19:11:38.368370
1,0.0,0.0,0.0,713000.0,0.0,False,0,3955137492069792,20231219,61050,713000.0,False,True,713000.0,0.0,0.0,0.0,2023-12-21 19:11:38.368370
2,0.0,0.0,0.0,713000.0,0.0,False,0,3955137492069792,20231218,61029,713000.0,False,True,713000.0,0.0,0.0,0.0,2023-12-21 19:11:38.368370
3,0.0,0.0,0.0,713000.0,0.0,False,0,3955137492069792,20231216,61130,713000.0,False,True,713000.0,0.0,0.0,0.0,2023-12-21 19:11:38.368370
4,0.0,0.0,0.0,713000.0,0.0,False,0,3955137492069792,20231213,61123,713000.0,False,True,713000.0,0.0,0.0,0.0,2023-12-21 19:11:38.368370
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385820,0.0,0.0,0.0,1000.0,0.0,False,0,26334665207205408,20121113,73010,1000.0,False,True,1000.0,0.0,0.0,0.0,2023-12-21 19:11:38.368370
385821,0.0,0.0,0.0,1000.0,0.0,False,0,26334665207205408,20121112,73010,1000.0,False,True,1000.0,0.0,0.0,0.0,2023-12-21 19:11:38.368370
385822,0.0,0.0,0.0,1000.0,0.0,False,0,26334665207205408,20121111,73002,1000.0,False,True,1000.0,0.0,0.0,0.0,2023-12-21 19:11:38.368370
385823,0.0,0.0,0.0,1000.0,0.0,False,0,26334665207205408,20121110,73010,1000.0,False,True,1000.0,0.0,0.0,0.0,2023-12-21 19:11:38.368370
385824,0.0,0.0,0.0,0.0,0.0,False,0,26334665207205408,20121107,73009,1000.0,False,True,1000.0,0.0,0.0,0.0,2023-12-21 19:11:38.368370

# TSETMC

## Market Watch

In [16]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [2]:
url = "https://old.tsetmc.com/tsev2/data/MarketWatchInit.aspx?h=0&r=0"

response = requests.get(url)

In [10]:
market_watch = BeautifulSoup(response.content).text

In [12]:
len(market_watch.split("@"))

5

In [30]:
market_watch.split("@")[0].split(",")

['164389', '1183081', '668953']

In [31]:
market_watch.split("@")[1].split(",")

['02/8/28 13:49:42',
 'P',
 '2026262.40',
 '(2316.64) -0.11%',
 '70359083527883136.00',
 '7681452598.00',
 '50599699246596.00',
 '309174',
 'P',
 '4822339088.00',
 '110968560436295.00',
 '215762',
 'P',
 '516947337.00',
 '1017766121480.00',
 '36492',
 '']

In [21]:
df = pd.Series(market_watch.split("@")[2].split(";")).apply(
    lambda c: pd.Series(c.split(","))
)

In [25]:
filt = df[2].str.contains("اراد")
df.loc[filt]

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
430,55938991037260979,IRB4SG6903A2,اراد692,مرابحه عام دولت69-ش.خ0310,61041,0,929200,929200,0,0,...,1,156,2,69,975660.00,882740.00,5000000,706,,
446,39633075506333957,IRB4SO130441,اراد112,مرابحه عام دولت112-ش.خ 040408,61041,0,1000000,1000000,0,0,...,1,200,2,69,1050000.00,950000.00,40000000,706,,
459,21066721937819577,IRB4O03404B1,اراد132,مرابحه عام دولت132-ش.خ041110,61040,0,943960,943960,0,0,...,1,196,2,69,991150.00,896770.00,80000000,706,,
497,42066300469778371,IRB4O0350541,اراد133,مرابحه عام دولت133-ش.خ050410,61040,0,929250,929250,0,0,...,1,162,2,69,975710.00,882790.00,75000000,706,,
587,21294020791802550,IRB4O0290461,اراد127,مرابحه عام دولت127-ش.خ040623,61040,0,999830,999830,0,0,...,1,156,2,69,1049820.00,949840.00,300000000,706,,
621,8897331139163152,IRB4SO090621,اراد108,مرابحه عام دولت108-ش.خ060218,61041,0,837310,837310,0,0,...,1,182,2,69,879170.00,795450.00,22000000,706,,
639,44883820260298236,IRB4O0290464,اراد1274,مرابحه عام دولت127-ش.خ040623,113513,910070,910070,910070,1,20357731,...,1,25,2,69,1999660.00,1.00,300000000,706,,
700,29990078640171531,IRB4SO1202A1,اراد111,مرابحه عام دولت111-ش.خ 021008,61041,0,977000,977000,0,0,...,1,124,2,69,1025850.00,928150.00,20000000,706,,
804,66381814486859895,IRB4SG870334,اراد874,مرابحه عام دولت87-ش.خ030304,105511,967709,967709,967709,1,22926700,...,1,28,2,69,1928540.00,1.00,100000000,706,,
877,24341706282853627,IRB4SG330332,اراد332,مرابحه عام دولت3-ش.خ 0303,61040,0,952000,952000,0,0,...,1,143,2,69,999600.00,904400.00,35000000,706,,
886,41997809087904044,IRB4SG7103B1,اراد71,مرابحه عام دولت71-ش.خ0311,61041,0,940000,940000,0,0,...,1,189,2,69,987000.00,893000.00,5000000,706,,
916,20610153643209375,IRB4O0310351,اراد129,مرابحه عام دولت129-ش.خ030510,61040,0,981300,981300,0,0,...,1,163,2,69,1030360.00,932240.00,50000000,706,,
995,29963964834392911,IRB4SG2402C1,اراد24,مرابحه عام دولت2-ش.خ ساير0212,61040,0,983000,983000,0,0,...,1,162,2,69,1032150.00,933850.00,26500000,706,,
999,43481364033628101,IRB4O02803C4,اراد1264,مرابحه عام دولت126-ش.خ031223,112942,934200,934200,934200,1,808159,...,1,28,2,69,2020000.00,1.00,130000000,706,,
1035,52909696671667929,IRB4SG960341,اراد96,مرابحه عام دولت96-ش.خ030414,61041,0,963000,963000,0,0,...,1,177,2,69,1011150.00,914850.00,50000000,706,,
1098,71479348014961494,IRB4SO0102B1,اراد100,مرابحه عام دولت100-ش.خ021127,61041,0,981460,981460,0,0,...,1,195,2,69,1030530.00,932390.00,50000000,706,,
1174,22067354885788211,IRB4SO170661,اراد116,مرابحه عام دولت116-ش.خ060630\t,61041,0,820000,820000,0,0,...,1,169,2,69,861000.00,779000.00,25000000,706,,
1183,23257748575526845,IRB4SG7203B1,اراد72,مرابحه عام دولت72-ش.خ0311,61041,0,987380,987380,0,0,...,1,189,2,69,1036740.00,938020.00,8000000,706,,
1242,40348118513018291,IRB4SG500321,اراد50,مرابحه عام دولت5-ش.خ0302,61040,0,999990,999980,0,0,...,1,166,2,69,1049980.00,950000.00,20000000,706,,
1257,44263351699841112,IRB4O0230382,اراد1222,مرابحه عام دولت122-ش.خ030807,61040,0,956640,956640,0,0,...,1,76,2,69,1004470.00,908810.00,42000000,706,,
1304,68429446337737591,IRB4SG870331,اراد87,مرابحه عام دولت87-ش.خ030304,61041,0,964270,968400,0,0,...,1,165,2,69,1012480.00,916060.00,100000000,706,,
1412,32425362809965324,IRB4O0360391,اراد134,مرابحه عام دولت134-ش.خ030907,61040,0,974270,974270,0,0,...,1,132,2,69,1022980.00,925560.00,50000000,706,,
1466,51576264644235785,IRB4SO200684,اراد1194,مرابحه عام دولت119-ش.خ060811\t,105534,840891,840891,840891,1,3500000,...,1,6,2,69,1917900.00,1.00,15000000,706,,
1535,9075805849723903,IRB4SO060351,اراد105,مرابحه عام دولت105-ش.خ030503,61041,0,979700,979700,0,0,...,1,180,2,69,1028680.00,930720.00,50000000,706,,
1716,64536596666647539,IRB4SG900521,اراد90,مرابحه عام دولت90-ش.خ050217,61041,0,939990,939990,0,0,...,1,195,2,69,986980.00,893000.00,30000000,706,,
1784,35385722970552859,IRB4SO210444,اراد1204,مرابحه عام دولت120-ش.خ040417\t,105631,918602,918602,918602,2,24921791,...,1,24,2,69,1858000.00,1.00,50000000,706,,
1850,69192306313524921,IRB4SO160661,اراد115,مرابحه عام دولت115-ش.خ060630,61041,0,910000,910000,0,0,...,1,177,2,69,955500.00,864500.00,30000000,706,,

In [27]:
pd.Series(market_watch.split("@")[3].split(";")).apply(
    lambda c: pd.Series(c.split(","))
)

                      0  1  2  3       4        5     6      7
0        87157161168095  1  1  0       0       50     0     29
1       114312662654155  1  4  1    4950     4970  1050   8859
2       204092872752957  1  1  1   36950    37550   136   5725
3       212813030943790  1  1  1  990000  1000000  2500   2500
4       270972009748578  1  1  0       0     2018     0      1
...                 ... .. .. ..     ...      ...   ...    ...
8761  23592632489955411  1  0  0       0        0     0      0
8762  23600798892801694  1  1  1    8520     8580  4862  67337
8763  23628030459637463  1  0  1    2369        0    33      0
8764  23669004423443369  1  0  1       1        0    11      0
8765  23709531360597343  1  0  1     100        0    30      0

[8766 rows x 8 columns]

In [32]:
market_watch.split("@")[4]

'12370968744'

## Datareader

In [1]:
from smdir.tsetmc import datareader

In [ ]:
symbol = "اراد142"

table = datareader.search(symbol)
filt = table["lVal18AFC"] == symbol
assert filt.sum() == 1
table.loc[filt, "insCode"].iloc[0]

In [2]:
datareader.update_price_from_source("ifb")

# IFB

## List

In [1]:
from smdir.metadata_reader import tables
from smdir.ifb import datareader
import pandas as pd

In [2]:
datareader.update_bond_page(from_source=True)

In [3]:
pd.read_parquet(tables.ifb.bond_list)

,record_id,document_id,row,symbol,publication_volume,acceptance_volume,nominal_amount_per_note,nominal_interest_rate,publication_date,market_maker_name,market_making_method,fluctuation_range,documents_and_records,description,received_time
0,32324,3883,1,مبتکران06,4000000,4000000,1000000,23%,1402-09-19,صندوق سرمایه‌گذاری اختصاصی بازارگردانی تثبیت پ...,مبتنی بر حراج,None,None,None,2023-12-21 17:14:56.045313
1,32278,3854,2,اراد146,60000000,60000000,1000000,20%,1402-09-14,فاقد بازارگردان,None,None,None,None,2023-12-21 17:14:56.045313
2,32266,3862,3,حیان06,2000000,2000000,1000000,23%,1402-09-11,شرکت تأمین سرمایه تمدن,مبتنی بر حراج,None,None,None,2023-12-21 17:14:56.045313
3,32259,3852,4,اراد145,80000000,80000000,1000000,20%,1402-09-07,فاقد بازارگردان,None,None,None,None,2023-12-21 17:14:56.045313
4,32215,3851,8,عالیفرد073,1000000,1000000,1000000,23%,1402-08-30,صندوق سرمایه‌گذاری اختصاصی بازارگردانی سهم آشن...,مبتنی بر حراج,None,None,None,2023-12-21 17:14:56.045313
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
551,14575,8,542,ماهان,291500,291500,1000000,20%,1389-12-21,تأميـن سرمايه نوين,مبتنی بر مذاکره,0/0500000007450581,None,None,2023-11-20 17:19:35.039062
552,14559,7,543,بعثت,200000,200000,1000000,20%,1389-10-28,تأميـن سرمايه امين,مبتنی بر مذاکره,0/0500000007450581,None,None,2023-11-20 17:19:35.039062
553,17810,6,544,مسکن1,20000000,8900000,1000000,20%,1389-10-05,كارگزاري بانك مسكن,مبتنی بر مذاکره,0/0500000007450581,None,None,2023-11-20 17:19:35.039062
554,14571,4,545,شرق,80000,80000,1000000,20%,1389-05-11,تأميـن سرمايه امين,مبتنی بر مذاکره,0/0500000007450581,None,None,2023-11-20 17:19:35.039062
555,14587,3,546,سعدی,300000,300000,1000000,17%,1389-04-26,تأميـن سرمايه نوين,مبتنی بر مذاکره,0/0500000007450581,None,None,2023-11-20 17:19:35.039062

# General

## Metadata

In [13]:
from smdir.metadata_reader import lib_settings

lib_settings.data_dir.parts

('D:\\', 'SMDIR', 'Data')

## Maintainer

In [1]:
from smdir.maintainer import update_files

update_files()

## PyArrow

In [11]:
import pyarrow

pyarrow.Table

pyarrow.lib.Table